### ISSUE TITLE
Serverstarter not working due to cursemeta downfall.

### ISSUE THREAD

**Issue by Gerald7777** [EnigmaticaModpacks/Enigmatica8#148]
### Modpack Version

Enigmatica8Server 1.0.5

### Describe your issue.

Cursemeta used by serverstarter was killed, making downloading server files impossible. It would be good idea to post alternate server files download until issue is resolved. 

[12:42:10] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=272335, fileID=3623830)
java.io.IOException: Request to https://cursemeta.dries007.net/272335/3623830.json was not successful.
	at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType.downloadMods$lambda-3(CursePackType.kt:203)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Gerald7777** [comment]
https://github.com/BloodyMods/ServerStarter/issues/67
More info about the issue on their side for reference.

**Comment by Quezler** [comment]
Already fixed in the enigmatic fork of serverstarter & as per fe7a1b2fde48983ce8bf7e443912bd34bc279114 in this repo, it only needs a new curseforge release :)

**Comment by Gerald7777** [comment]
Awesome! Until it rolls in workaround seems to be just to copy the client pack and remove moreoverlays-1.20.4-mc1.18.jar from server mods. Feel free to close the issue when deemed appropriate.

**Comment by AzureDoom** [comment]
> Already fixed in the enigmatic fork of serverstarter & as per [fe7a1b2](https://github.com/EnigmaticaModpacks/Enigmatica8/commit/fe7a1b2fde48983ce8bf7e443912bd34bc279114) in this repo, it only needs a new curseforge release :)

Their fork is still using CurseMeta so they will run into the issue of it not downloading any uploaded mod files after the API switch over.

**Comment by NielsPilgaard** [comment]
> Their fork is still using CurseMeta so they will run into the issue of it not downloading any uploaded mod files after the API switch over.

Is the original ServerStarter using something else now?

**Comment by Darkere** [comment]
Not sure what Azure doom is talking about. Original Serverstarter doesn't have a solution yet.

**Comment by AzureDoom** [comment]
It does not, I've been working on my own fork of the original starter to switch to the official API as I have an API key to use. CurseMeta is dead and you won't be to use it download mods anymore.
