### ISSUE TITLE
net.minecraft.world.entity.projectile.AbstractArrow.m_5603_(AbstractArrow.java:422) + ServerHangWatchdog took 300.00+ seconds (should be max 0.05)

### ISSUE THREAD

**Issue by mjevans** [EnigmaticaModpacks/Enigmatica8#222]
### Modpack Version

E8 2.1.0

### Describe your issue.

The server I've run experienced two lockups today alone that appear related to AbstractArrow.  According to user reports, the most likely interaction was a user who'd baited Illagers into attacking each other with their crossbows.

Since this doesn't seem to be a vanilla issue (didn't see many any obvious results for 'AbstractArrow'), I further speculate that the mobs might sometimes spawn with modded enchantments.

There didn't appear to be anything noteworthy in the vanilla server console for other of these lockups.

**Is there a way more data can be collected to better isolate this issue?**  The crash logs aren't terribly illustrative as the object dump of the stalled thread isn't included.  Additionally one would think a timeout of 20x vanilla tick time should be added to such traveling entities rather than allowed to iterate forever.

### Crash Report

https://gist.github.com/mjevans/9c78bb11ca188a067b76b44bb6f1fe61

### Have you modified the modpack?

Yes

### User Modifications

Some of the development committed changes for ore generation (one type of ore) and such.  One other crash may have been related to a world pregeneration mod that was added, which has since been disabled (but still installed); that is omitted from this bug report.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Hmm, I wonder if this could be caused by the Piercing enchant from Quark 🤔

**Comment by mjevans** [comment]
It might be https://www.curseforge.com/minecraft/mc-mods/parry

Slightly different but possibly related crash:

    java.lang.Error: ServerHangWatchdog detected that a single server tick took 90.00 seconds (should be max 0.05)
        at java.lang.StrictMath.log(Native Method) ~[?:?] {}
        at java.util.Random.nextGaussian(Random.java:528) ~[?:?] {re:mixin}
        at net.minecraft.world.entity.projectile.Projectile.m_6686_(Projectile.java:114) ~[server-1.18.2-20220404.173914-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.entity.projectile.AbstractArrow.m_6686_(AbstractArrow.java:105) ~[server-1.18.2-20220404.173914-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:accessor.AccessorAbstractArrow,pl:mixin:A}
        at us.drullk.parry.ShieldParry.lambda$parryThisCasual$0(ShieldParry.java:62) ~[parry-2.3.jar%23216!/:2.3] {re:classloading}
        at us.drullk.parry.ShieldParry$$Lambda$44973/0x00000008057bbea0.accept(Unknown Source) ~[?:?] {}
        at us.drullk.parry.ShieldParry.parryProjectile(ShieldParry.java:45) ~[parry-2.3.jar%23216!/:2.3] {re:classloading}
        at us.drullk.parry.ShieldParry.dispatchShieldParry(ShieldParry.java:56) ~[parry-2.3.jar%23216!/:2.3] {re:classloading}
        at us.drullk.parry.ShieldParry.parryThisCasual(ShieldParry.java:61) ~[parry-2.3.jar%23216!/:2.3] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_260_ShieldParry_parryThisCasual_ProjectileImpactEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus$$Lambda$4294/0x0000000801bd51b8.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:644) ~[forge-1.18.2-40.1.68-universal.jar%23308!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(AbstractArrow.java:187) ~[server-1.18.2-20220404.173914-srg.jar%23303!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:accessor.AccessorAbstractArrow,pl:mixin:A}

**Comment by NielsPilgaard** [comment]
Ah that might be! @Drullkus could you please assist us here? We have a crash possibly caused by Parry above :)
