### ISSUE TITLE
Exploration / Chunk Generation casuing crash 

### ISSUE THREAD

**Issue by Alnarra** [EnigmaticaModpacks/Enigmatica8#281]
### Modpack Version

2.3.0

### Describe your issue.

This appears to be coming from Patchouli in a way, I'm not exactly clear on which part is actually causing it, I have attached the latest.log including the crash. 

This happens as my players are exploring the map / generating new chunks 

### Latest Log

https://gist.github.com/Alnarra/ba48573f68ff5af3e8a021dabd8766de

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Alnarra#3724

**Comment by NielsPilgaard** [comment]
There's no crash in your latest.log sadly, do you not have a crash report? :)

**Comment by Alnarra** [comment]
```
[19Sep2022 15:47:41.319] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book xnet:manual defined by mod xnet, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.323] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book rftoolsbuilder:manual defined by mod rftoolsbuilder, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.324] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book toomanyglyphs:worn_notebook defined by mod toomanyglyphs, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.328] [modloading-worker-0/INFO] [mcjtylib/]: RFTools Storage Detected XNet: enabling support
[19Sep2022 15:47:41.328] [modloading-worker-0/INFO] [potionstudios.byg.BYG/]: "/home/container/config/byg/overworld/byg-overworld-biomes.json5" was read.
[19Sep2022 15:47:41.327] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book deepresonance:manual defined by mod deepresonance, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.328] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book rftoolspower:manual defined by mod rftoolspower, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.331] [modloading-worker-0/INFO] [potionstudios.byg.BYG/]: "/home/container/config/byg/byg-biome-dictionary.json" was read.
[19Sep2022 15:47:41.333] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book aiotbotania:lexicon defined by mod aiotbotania, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.341] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book rftoolsutility:manual defined by mod rftoolsutility, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[19Sep2022 15:47:41.344] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book rftoolsstorage:manual defined by mod rftoolsstorage, skipping
com.google.gson.JsonSyntaxException: Missing name, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23322!/:?]
	at vazkii.patchouli.common.book.Book.<init>(Book.java:122) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:116) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:76) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:71) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:59) ~[Patchouli-1.18.2-71.1.jar%23228!/:1.18.2-71.1]
	at net.minecraftforge.eventbus.ASMEventHandler_589_ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.80.jar%23324!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.80.jar%23323!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

Is the crash sequence that occurs, each time it's occuring it forces a server restart and kicks all players.

**Comment by Alnarra** [comment]
Actually scratch this one, I'm fairly sure this is on my side. I believe that the kubejs folder didn't get updated from 2.1 to 2.3 like it should have been when I updated the server side stuff. That is likely the root cause of this
