### ISSUE TITLE
Can't enter Compact Machines

### ISSUE THREAD

**Issue by Chucko573** [EnigmaticaModpacks/Enigmatica8#61]
### Modpack Version

1.05 Beta

### Describe your issue.

I cannot enter any Compact Machine or teleport to any waypoints for the Compact Dimension.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Chucko573** [comment]
So, I discovered that new worlds work fine with compact machines.  It's just the world I updated from 1.04 to 1.05 Beta that no longer shows the Compact Machines dimension as being available.

**Comment by NillerMedDild** [comment]
Oh boy. Does removing the dimension folder from your world folder regenerate it?

**Comment by Chucko573** [comment]
> Oh boy. Does removing the dimension folder from your world folder regenerate it?

No, it does not.  

Also the Compact Machines Dimension did not appear in the TPS report before or after doing so.

**Comment by NillerMedDild** [comment]
Damn :/ would you mind reporting this on the Compact Machines GitHub?

**Comment by Chucko573** [comment]
> Damn :/ would you mind reporting this on the Compact Machines GitHub?

Will do.

**Comment by zigonick** [comment]
Can also confirm this happens in multiplayer when upgrading from 1.04 to 1.05. Deleting the compact machine demnisions folder does not fix the issue. Server logs. When attempting to enter machine. 

[19:50:04] [Server thread/ERROR]: No compact dimension found. Report this.
[19:50:05] [Server thread/ERROR]: No compact dimension found. Report this.
[19:50:05] [Server thread/WARN]: Compact dimension not found; player attempted to enter machine.
[19:50:05] [Server thread/ERROR]: No compact dimension found. Report this.
[19:50:06] [Server thread/ERROR]: No compact dimension found. Report this.


And when placing down a new machine

[19:51:35] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "dev.compactmods.machines.data.persistent.CompactMachineData.setMachineLocation(int, dev.compactmods.machines.teleportation.DimensionalPosition)" because "extern" is null
        at dev.compactmods.machines.block.CompactMachineTile.doPostPlaced(CompactMachineTile.java:166) ~[compactmachines-4.0.0-beta.4.jar%2367!/:4.0.0-beta.4]
        at dev.compactmods.machines.block.BlockCompactMachine.m_6402_(BlockCompactMachine.java:177) ~[compactmachines-4.0.0-beta.4.jar%2367!/:4.0.0-beta.4]
        at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:77) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:592) ~[forge-1.18.1-39.0.63-universal.jar%23238!/:?]
        at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23234!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:51:35] [Server thread/ERROR]: No compact dimension found. Report this.
